TARGET = uart

XRAM_SIZE = 0x0300
XRAM_LOC = 0x0000

FREQ_SYS = 24000000

EXTRA_FLAGS = --opt-code-speed

C_FILES = \
	main.c \
	../ch554_sdcc/include/debug.c

include ../ch554_sdcc/examples/Makefile.include
